### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aowoWolf** [ikesnowy/Algorithms-4th-Edition-in-Csharp#321]
[Fundamental_1.4.15](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/master/1%20Fundamental/1.4/1.4.15/Program.cs)的54行中while的判断应该为"<"，不然对于```{-3,-2,2,3}```这样对称的数组，会出现下标越界的异常

**Comment by ikesnowy** [comment]
Thx，已修复。[修复 1.4.15 的一处越界问题 ](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/commit/52958179c1cdfb9f1da64159ef5cec3799624d73)
