### ISSUE TITLE
1.4.18 解法有问题

### ISSUE THREAD

**Issue by jonyzhao** [ikesnowy/Algorithms-4th-Edition-in-Csharp#536]
测试用例： 1、2、3、4、5、7、6、8，找不到局部最小值6，而是返回-1

**Comment by jonyzhao** [comment]
如果定义局部最小值包含边界值，那么这个rolling down的思路是没问题的，只要注意下下标溢出问题就可以。否则应当每次二分后，先递归找右半边，如果找不到，再找左边。

**Comment by ikesnowy** [comment]
这里假设边界值也属于局部最小，修改了算法以满足题目中对于比较次数的要求。
