### ISSUE TITLE
Bug：1.3.31

### ISSUE THREAD

**Issue by ljdhhp** [ikesnowy/Algorithms-4th-Edition-in-Csharp#539]
删除表头元素函数中，删除表头后是否应该将第二个节点的prev指针显式置为null（假如原来的节点数>=2）?

**Comment by ikesnowy** [comment]
Fixed at https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/commit/d95c5caa5751de3cc02c5bdd3b28145b939340fd
