### ISSUE TITLE
1.1.14是否可用二进制十进制转换计算

### ISSUE THREAD

**Issue by morganfreemanX** [ikesnowy/Algorithms-4th-Edition-in-Csharp#586]
static int lg(int N)
        {
            string nBinary = Convert.ToString(N, 2);
            int nLength = nBinary.Length;
            int result = 0;

            result = Int32.Parse(nBinary[0] + "");
            result *= nLength - 1;

            return result;
        }

**Comment by ikesnowy** [comment]
你好，可以的。

关于这类的方法的测试可以参考这个链接，那边讨论的是取十进制最高位，二进制结果应该类似：

https://stackoverflow.com/questions/701322/how-can-you-get-the-first-digit-in-an-int-c/701621#701621

**Comment by morganfreemanX** [comment]
感谢引申
