### ISSUE TITLE
2.3.20 测试结论相反, 发现是因为Stack的原因

### ISSUE THREAD

**Issue by zxt385189207** [ikesnowy/Algorithms-4th-Edition-in-Csharp#587]
大佬,你自己写个Stack得出这结论不太靠谱啊
"由于栈操作比函数调用操作耗费时间更长，因此测试后的结果会比原有快排慢 20% 左右。"

用System.Collections.Generic.Stack的输出如下:
n       non-recursive   normal  ratio
200000   49.5            49.75   0.994974874371859
400000  101.25          104.75  0.966587112171838
800000  215.75          215.75  1
1600000 453.75          458.25  0.990180032733224
3200000 960.75          977.25  0.983115886415963

**Comment by ikesnowy** [comment]
emmm，我换成了 System.Collections.Generic.Stack，结果还是一样的（Release）。

```
n       non-recursive   normal  ratio
200000  23.25           18.25   1.273972602739726
400000  43              36.5    1.178082191780822
800000  86              73.75   1.1661016949152543
1600000 178.5           156.25  1.1424
3200000 376.5           328     1.1478658536585367
```

就改了两行代码

```
public override void Sort<T>(T[] a)
{
    Shuffle(a);
    var stack = new System.Collections.Generic.Stack<int>();
    stack.Push(0);
    stack.Push(a.Length - 1);

    while (stack.Count != 0)
    {
        // 压入顺序是先 lo，再 hi，故弹出顺序是先 hi 再 lo
        var hi = stack.Pop();
        var lo = stack.Pop();

        if (hi <= lo)
            continue;

        var j = Partition(a, lo, hi);

        // 让较大的子数组先入栈（先排序较小的子数组）
        if (j - lo > hi - j)
        {
            stack.Push(lo);
            stack.Push(j - 1);

            stack.Push(j + 1);
            stack.Push(hi);
        }
        else
        {
            stack.Push(j + 1);
            stack.Push(hi);

            stack.Push(lo);
            stack.Push(j - 1);
        }
    }
    Debug.Assert(IsSorted(a));
}
```

如果用的是 Debug 的话，结果好像是差不多的。

![image](https://user-images.githubusercontent.com/17109152/76720239-35d2d480-6777-11ea-8511-828c18e301b9.png)

```
n       non-recursive   normal  ratio
200000  86.25           77.25   1.116504854368932
400000  162.5           160.5   1.0124610591900312
800000  351.75          336     1.046875
1600000 734.5           716.5   1.0251221214235868
3200000 1543.5          1494.75 1.0326141495233316
```

**Comment by zxt385189207** [comment]
我也只改了2行, Release情况下也是1.0左右占多数.. 1.2基本看不到..

**Comment by zxt385189207** [comment]
尴尬了.. 结论没问题, 就是20%说高了... 

System.Collections.Generic.Stack
               debug
                200000   49.25           49.5    0.994949494949495
                400000  102.5           101.75  1.00737100737101
                800000  219.75          216.25  1.01618497109827
                1600000 457.75          458.25  0.998908892525914
                3200000 967.25          983.5   0.983477376715811

                release
                200000   17.75           15.75   1.12698412698413
                400000  35.25           32.25   1.09302325581395
                800000  71.75           64.5    1.11240310077519
                1600000 149.75          140     1.06964285714286
                3200000 338.75          313     1.08226837060703
       

Stack
        debug
        200000   63.25           50      1.265
        400000  125             103.75  1.20481927710843
        800000  264.75          216.25  1.2242774566474
        1600000 547.75          462.25  1.18496484586263
        3200000 1179.75         986.5   1.19589457678662

        release
        200000   21              15.25   1.37704918032787
        400000  39.5            32      1.234375
        800000  79.5            65.75   1.20912547528517
        1600000 168.25          142.25  1.18277680140598
        3200000 361.5           314.25  1.15035799522673

**Comment by ikesnowy** [comment]
我更新了一下截图，去掉了引起误解的 20%

https://alg4.ikesnowy.com/2-3-20/
