### ISSUE TITLE
2.2.12 所需的额外空间不对

### ISSUE THREAD

**Issue by w1374720640** [ikesnowy/Algorithms-4th-Edition-in-Csharp#588]
题目要求：使所需的额外空间减小到max(M,N/M)，但是你的代码中创建了(N/M - 1)个大小为M的数组，需要的总额外空间为：(N/M - 1) * M 约等于N，某一时刻的额外空间为M，不符合题目要求

**Comment by ikesnowy** [comment]
已修复
