### ISSUE TITLE
关于习题1.4.13的疑问

### ISSUE THREAD

**Issue by aqiao** [ikesnowy/Algorithms-4th-Edition-in-Csharp#589]
你好大神:
看了一下关于1.4.13的答案,有两个疑问:
1.书中提到引用类型变量需要占8个字节,`FixedCapacityStackOfString`里有一个`String`数组, 因为数组本身也是对象,所以应该包含这个数组变量对应的8个字节,我的计算结果是:
16(对象头) + 8(String[] 变量) + 4(int 变量) + 4(填充) = 32,如果还要包含String数组实际大小时,应该是 `32 + (64 + 2N) * C`. 注意,这里的N表示每个字符串的平均长度

2. `Point2D` 明明包含如下变量:
```
  /**
   * Compares two points by x-coordinate.
   */
  public static final Comparator<Point2D> X_ORDER = new XOrder();

  /**
   * Compares two points by y-coordinate.
   */
  public static final Comparator<Point2D> Y_ORDER = new YOrder();

  /**
   * Compares two points by polar radius.
   */
  public static final Comparator<Point2D> R_ORDER = new ROrder();
```
而且三个变量都是引用类型,每个应该占有8个字节,为什么不统计它们,而单单统计double类型的变量?

**Comment by ikesnowy** [comment]
这看起来不像是我的代码，而且我看到你在小黑的 repo 下提了一模一样的 issue，是不是提错地方了？

**Comment by aqiao** [comment]
上面的带代码是书中的代码,放在这只是为了方便说明问题. 因为不太确定你会不会回复所以就在多个repo上提了相同的问题.
这个应该是你的答案连接:https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/master/1%20Fundamental/1.4/1.4.13/Program.cs
所以麻烦回答一下上面的问题

**Comment by ikesnowy** [comment]
我不是很喜欢这种“聪明”的方式，就和群发祝福一样让人感受不到尊重，尤其是当连续收到两封一样的“祝福”的时候（我 watch 了小黑的 repo），给人的感觉就更糟糕了。

1. 你已经提到了，数组也是对象，对象会有 16 字节的固定开销（即“对象头”），因此引用一个空数组需要 8（引用）+16（数组对象）= 24 字节，在你的式子中加上 16 字节就可以得到答案。

2. 它们是静态的（`static`），你只能通过类名访问它们（`Point2D.X_ORDER`），也就是说，在实例对象里面并没有保存这些静态成员的引用（它们是类的成员而非对象的成员），因此在计算对象开销时候没有计入。

**Comment by aqiao** [comment]
我是担心你们都不回复所以提了两个issue, anyway 很抱歉让你感到不受尊重
