### ISSUE TITLE
练习1.1.1网站上的答案有误

### ISSUE THREAD

**Issue by 5ME** [ikesnowy/Algorithms-4th-Edition-in-Csharp#592]
练习1.1.1 求表达式的值
b. `2.0e-6 * 100000000.1`

https://alg4.ikesnowy.com/1-1-1/ 网站的给出的答案是 1562500.0015625，应该不对吧，希望更正

**Comment by ikesnowy** [comment]
感谢，代码改完之后忘记改题解了
