### ISSUE TITLE
1-4-9 中的公式

### ISSUE THREAD

**Issue by Higurashi-kagome** [ikesnowy/Algorithms-4th-Edition-in-Csharp#594]
[1-4-9](https://alg4.ikesnowy.com/1-4-9/) 中的第一行公式似乎少了些换行，而且中间有一个红色的反斜杠：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/154439555-78bd0783-06c9-4713-9297-022ddaf50ce0.png)

</details>

感谢维护。

**Comment by Higurashi-kagome** [comment]
另外，[1-4-18](https://alg4.ikesnowy.com/1-4-18/) 中的行内公式未正常显示：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/154655585-0d0b0266-04fa-48fd-a385-c3c9ca693dff.png)

</details>

**Comment by ikesnowy** [comment]
我在更换公式渲染引擎，现在有问题的是正常的，完成后会更新 issue 状态。

**Comment by ikesnowy** [comment]
换成 katex 了，现在应该可以了。
