### ISSUE TITLE
1-4-15 ThreeSumFaster 中的 while 循环条件

### ISSUE THREAD

**Issue by Higurashi-kagome** [ikesnowy/Algorithms-4th-Edition-in-Csharp#595]
[1.4.15/Program.cs#L76](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/4010624266818db4261dcd968f287f0712d52d48/1%20Fundamental/1.4/1.4.15/Program.cs#L76) 中，似乎应该是 `lo < hi`。

**Comment by Higurashi-kagome** [comment]
另：[1.4.20/Program.cs#L70](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/4010624266818db4261dcd968f287f0712d52d48/1%20Fundamental/1.4/1.4.20/Program.cs#L70) 中似乎应该是 `lo <= hi`。

**Comment by ikesnowy** [comment]
感谢你的反馈，但没有具体理由的话，我会先把时间放在有明确内容的其他事情上，你的 issue 会延后处理。

**Comment by Higurashi-kagome** [comment]
> [1.4.15/Program.cs#L76](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/4010624266818db4261dcd968f287f0712d52d48/1%20Fundamental/1.4/1.4.15/Program.cs#L76) 中，似乎应该是 `lo < hi`。
> 

求 `{-4, 0, 2, 3}` 的三元组返回 1，实际上应该是 0。

> 另：[1.4.20/Program.cs#L70](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/4010624266818db4261dcd968f287f0712d52d48/1%20Fundamental/1.4/1.4.20/Program.cs#L70) 中似乎应该是 `lo <= hi`。

在 `{5,4}` 中找 4，返回 -1，实际上应该是 1。

**Comment by ikesnowy** [comment]
感谢，已经修复了这两个问题
