### ISSUE TITLE
公式显示失效

### ISSUE THREAD

**Issue by Higurashi-kagome** [ikesnowy/Algorithms-4th-Edition-in-Csharp#596]
如 [1-4-26](https://alg4.ikesnowy.com/1-4-26/)、[1-4-32](https://alg4.ikesnowy.com/1-4-32/)。

**Comment by ikesnowy** [comment]
感谢！Katex 的语法规则比较严格，$$ 前面必须要有空行才行，我用正则尽量修复了一些，如果还有问题的话随时提 issue。

近期打算迁移站点到 hugo 或者 gastby 上去，hexo 处理 447 篇博文已经有些吃力了。
