### ISSUE TITLE
夜间模式下的代码背景为浅色

### ISSUE THREAD

**Issue by Higurashi-kagome** [ikesnowy/Algorithms-4th-Edition-in-Csharp#597]
<details>
<summary><a href="https://alg4.ikesnowy.com/3-3-5/">3-3-5</summary>

![image](https://user-images.githubusercontent.com/51501079/154843138-10253446-b915-4815-acfd-31ec341e28a3.png)

</details>

**Comment by ikesnowy** [comment]
为了显示速度目前代码块采用服务端渲染的方式（也就是我本地渲染好直接传上去的），因此代码高亮暂时没法自适应。

迁移到 hugo 之后我会看看有没有机会恢复这个功能。
