### ISSUE TITLE
搜索似乎不能正常工作

### ISSUE THREAD

**Issue by Higurashi-kagome** [ikesnowy/Algorithms-4th-Edition-in-Csharp#611]
我在搜索框中输入内容，不能够正常过滤（无反应）：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/158725355-a282cda8-1cbd-449e-ba64-e7cb909b5bf2.png)

</details>

虽然其实用浏览器自带的搜索功能也很方便。

**Comment by ikesnowy** [comment]
修好了，现在可以输编号或者英文搜索。

中文搜索现在还没有，等之后有空研究一下
