### ISSUE TITLE
2.2.11 中对去除数组复制的分析

### ISSUE THREAD

**Issue by Higurashi-kagome** [ikesnowy/Algorithms-4th-Edition-in-Csharp#612]
在 [2-2-11.md](https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/blob/master/docs/content/2-2-11.md) 中，有这样一段分析：

> 归并次数总是一个奇数（左侧归并+右侧归并+总归并），因此在第一次调用 Sort 方法时应该把 aux 和 a 互换传入。

似乎并不正确，比如归并长度为 3 的数组 a，第一次归并 a[0]、a[1]，第二次归并 a[0..1]、a[2]，总共归并两次。不知道是不是我理解错了。

这里有一种值得考虑的解释：

```
先创建 a 的一个副本 aux。
要将 a 排序，先将 aux 二分为两个子数组，并分别排序，然后将 aux 归并到 a 中。
要将 aux 的子数组排序，先将 a 中对应的子数组二分，并分别排序，然后将 a 中排好的子数组归并到 aux 中。
如此持续。
```

所以“第一次调用 Sort 方法时把 aux 和 a 互换传入”是因为“要先把 aux 二分并排好序，然后将结果归并到 a 中”：Merge(src, dst, lo, mid, hi) 是在将 src 归并到 dst 中，所以 Sort(T[] src, T[] dst, int lo, int hi) 排序的是 dst，所以应该将 a 传给 dst，将 aux 传给 src，以使得 aux 被二分并排序，最后归并到 a 中。

```c#
Sort(dst, src, lo, mid);			// 将 src 左半边排序
Sort(dst, src, mid + 1, hi);	// 将 src 右半边排序
Merge(src, dst, lo, mid, hi);	// 将 src 归并到 dst
```

**Comment by ikesnowy** [comment]
你的理解应该是正确的。

奇数这个思路是这样的：这个优化过的归并排序的依赖树是一个完满二叉树（Full Binary Tree，对于任意结点，它要么没有子结点，要么有两个子结点）->完满二叉树的结点数总是一个奇数->奇数次交换会导致最后结果互换->需要补一次交换使其变为偶数

我忘记这里有个插入排序优化了，改成调用 `Sort()` 次数应该就 ok 了。

**Comment by Higurashi-kagome** [comment]
好的，谢谢。
