### ISSUE TITLE
[BUG]1.1.25 可以在第二步证明公约数是最大公约数部分用第二类数学归纳法证明

### ISSUE THREAD

**Issue by pezy-boy** [ikesnowy/Algorithms-4th-Edition-in-Csharp#615]
**题号**

哪一道题出现了问题？1.1.25

**出现的错误**

出错的地方，以及相关的说明。（例如：在 xxx 情况下会出现错误，xxx 的条件有问题）
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/62460970/174622546-20f241ec-b875-476b-b442-e60e2def9de0.png">

**可能的正确答案（可不填）**
当n=1，2时，命题成立；即r1 与 r2 能够被g整除
假设当n <= k时，命题成立, 即 rk = mg  rk-1 = ng， 从而可证 rk+1可被g整除。
对一切正整数n都成立，所以rn-1 >= g
所以 rn-1 = g

**Comment by ikesnowy** [comment]
确实没有在题解中体现数学归纳法的部分，我改进一下。
